### ISSUE TITLE
Video Marquee Component

### ISSUE THREAD

**Issue by prewalia** [grommet/hpe-digitaltoolkit#103]

**Comment by kyle-locke** [comment]
FYI, I removed 'option 1' from the sketch file.
[hpe-video-component-r2-kl.sketch.zip](https://github.com/grommet/hpe-digitaltoolkit/files/370164/hpe-video-component-r2-kl.sketch.zip)

**Comment by prewalia** [comment]
Hey guys sorry about the confusion :) here are all the files:

**PDF showing transition** from the current Video Marquee space (where we would be playing the looping video) to the video player once you click on "Watch Now". As you can see once you click on "Watch Now" the content below gets pushed further down to accommodate 16:9 format of the actual video:
[VideoMarquee_To_Player_Transition.pdf](https://github.com/grommet/hpe-digitaltoolkit/files/370177/VideoMarquee_To_Player_Transition.pdf)


**The final sketch file** (So this can simply be inserted in the current video marquee space playing inline(vs layer). Added the close X and resized play/pause icons to core grommet 24px, and added our replay/share screen. The video will play inline on page by replacing the video marquee initial state. Height will grow from marquee height, 75% or whatever it is now, to accommodate 16:9 format of the actual video): 
(Kyle has uploaded the updated version above/in the post before this one) 

**The PDF file for the same/sketch file**:
hpe-video-component-r2-kl.pdf

**Comment by phuson** [comment]
@prewalia 

Question regarding the Video component: What date time format should we be using for the current time and duration display (0:05 / 4:09) in the latest design? Is it `minute:second` or `hour:minute`?

Also, does the new Play icon (filled in version) exist in Grommet core (http://www.grommet.io/docs/develop/icon)?

**Comment by kyle-locke** [comment]
@phuson minute:second, thanks!

**Comment by phuson** [comment]
@kyle-locke if that's the case (minute:second), what if the video is longer than an hour, how should we display that?

**Comment by kyle-locke** [comment]
@phuson If possible we could just add another set of digits if video length = 01:02:03. Can that be done conditionally if the video is longer than an hour? Or do we always have to show all? I highly doubt there will be a lot of long form videos. CC @L0ZZI Chris, do we need to support this case?

**Comment by kyle-locke** [comment]
[hpe-video-component-r3-kl.pdf](https://github.com/grommet/hpe-digitaltoolkit/files/391274/hpe-video-component-r3-kl.pdf)
[hpe-video-component-r3-kl.zip](https://github.com/grommet/hpe-digitaltoolkit/files/391273/hpe-video-component-r3-kl.zip)
