### ISSUE TITLE
Card content is not wrapping

### ISSUE THREAD

**Issue by mdctenga** [grommet/hpe-digitaltoolkit#122]
## Objective

- Cards should look like this: ![correct-cards](https://cloud.githubusercontent.com/assets/8364525/18021223/9f34689e-6b81-11e6-8fd1-a4c89452bbd1.png)

### Steps to Reproduce

1. Navigate to [hpe-toolkit.herokuapp.com/docs/examples](hpe-toolkit.herokuapp.com/docs/examples) from a PC using Internet Explorer: Version 11.545.10586.0
    - Notice the cards look like this: ![card content mushed](https://cloud.githubusercontent.com/assets/8364525/18021224/9f3a5e98-6b81-11e6-93e5-2f522737310b.PNG)

**Comment by jwijay** [comment]
grommet-core PR pending: https://github.com/grommet/grommet/pull/846
