### ISSUE TITLE
(Windows 10/IE11) Content Card w/ Tiles Wrapper always in mobile state

### ISSUE THREAD

**Issue by mdctenga** [grommet/hpe-digitaltoolkit#123]
## Objective

- ![correct-card-tile-wrapper-behavior](https://cloud.githubusercontent.com/assets/8364525/18023962/0ed2c7ee-6b9c-11e6-9a11-821a65a8755a.gif)

### Steps to Reproduce

1. Navigate to [hpe-toolkit.herokuapp.com/docs/hpe/examples](hpe-toolkit.herokuapp.com/docs/hpe/examples) from Internet Explorer Version 11.545.10586.0 using a PC
    - Notice that the Card w/ Tiles Wrapper is always in mobile state ![always in mobile state](https://cloud.githubusercontent.com/assets/8364525/18022281/2f40a52c-6b89-11e6-8288-510efe3732e1.PNG)

**Comment by jwijay** [comment]
grommet-core PR pending: https://github.com/grommet/hpe-digitaltoolkit/issues/123

**Comment by mdctenga** [comment]
Currently still in mobile state on Windows 10/IE11 ![screen shot 2016-10-04 at 11 20 59 am](https://cloud.githubusercontent.com/assets/8364525/19092974/ec7e5990-8a24-11e6-9a61-6e10bdba03b6.png)

**Comment by jwijay** [comment]
PR Pending: https://github.com/grommet/grommet/pull/937
