### ISSUE TITLE
Unnecessary content in the background

### ISSUE THREAD

**Issue by mdctenga** [grommet/hpe-digitaltoolkit#124]
# Issue affects the following environments

- Chrome 52 (Mac/PC/iOS/Android)
- Firefox 48 (Mac/PC/iOS/Android)
- Safari 9.1.2 (Mac/iOS)

## Objective

- There should be no content in the background behind cards

### Steps to Reproduce

1. Navigate to [http://hpe-toolkit.herokuapp.com/docs/hpe/examples](http://hpe-toolkit.herokuapp.com/docs/hpe/examples)
2. Scroll over cards section while the view is < 619 px to see "Main Content" links behind the cards ![unnecessary-content-in-background](https://cloud.githubusercontent.com/assets/8364525/18068274/4705fd42-6ddc-11e6-9b8d-4b6f97f1b960.gif)

**Comment by jwijay** [comment]
This is not a toolkit bug, but an issue with Skip Links in grommet-core still being visible (and positioned beneath app content), and not wrapping.

![skip-links-bug](https://cloud.githubusercontent.com/assets/10161095/18371724/70def77e-75d2-11e6-889a-439b8006faf1.gif)

**Comment by jwijay** [comment]
Closing this issue, since it's been resolved by merged grommet-core PR: 
https://github.com/grommet/grommet/pull/840
