### ISSUE TITLE
Content card does not span full mobile width

### ISSUE THREAD

**Issue by mdctenga** [grommet/hpe-digitaltoolkit#126]
## Objective

Card should be the width of the mobile device as seen in the [designs](https://hp.invisionapp.com/share/J481W2OX5#/screens)

### Steps to Reproduce

1. Navigate to [http://hpe-toolkit.herokuapp.com/docs/hpe/examples](http://hpe-toolkit.herokuapp.com/docs/hpe/examples)
2. Using a mobile device or setting your browser width to 719px width see that cards have 24px padding on both sides of the cards
![screen shot 2016-09-05 at 4 28 02 pm](https://cloud.githubusercontent.com/assets/8364525/18260710/2c9044a8-738c-11e6-8590-3ab3db120aa9.png)
    - Issue affects both Android (Chrome, Firefox) and iOS (Chrome, Firefox, Safari)

**Comment by jwijay** [comment]
Fixed peeking background issue (paragraph max-width was preventing card from fully expanding width-wise in the column): https://github.com/grommet/grommet/pull/831

To make the line separator expand the full-width of the screen/window, the padding needs to be removed on the wrapping Box container. Having the padding removed for mobile (palm media query) only on the box wrapping the cards would be a custom style.

**Screenshot with removed `pad={{horizontal: 'large'}}` attribute on Box wrapping cards:**

![screen shot 2016-09-08 at 12 10 35 pm](https://cloud.githubusercontent.com/assets/10161095/18368751/5d2fcc04-75bd-11e6-9a82-9cc1b73a159d.png)

**Comment by mdctenga** [comment]
Mike made the call that full-width cards on mobile is not mandatory.
