### ISSUE TITLE
(iOS/Chrome) Section text container goes full section height

### ISSUE THREAD

**Issue by mdctenga** [grommet/hpe-digitaltoolkit#136]
# Issue also affects 
    
    - iOS / Firefox

## Objective 

- text box should have space between top and bottom of section
- For reference: https://github.com/grommet/hpe-digitaltoolkit-design/issues/31

### Steps to Reproduce

1. Open any browser and resize width to anywhere between 719px - 1161px
    - ![img_0004](https://cloud.githubusercontent.com/assets/8364525/18891332/785d9078-84a0-11e6-9139-60eea113de33.PNG)

**Comment by jwijay** [comment]
Responsive font sizes have been re-added to Marquee component:
![screen shot 2016-10-03 at 2 36 49 pm](https://cloud.githubusercontent.com/assets/10161095/19058887/ef9b11d0-8976-11e6-8d5d-af534b59642f.png)

(screenshot of Section component between 719px and 1024px in Chrome)

**Comment by mdctenga** [comment]
@MikeWalrath said this is complete as is and the burden will be on the writers to make sure they don't use an excessive amount of content.
