### ISSUE TITLE
(Android/Firefox) "..." truncation does not display

### ISSUE THREAD

**Issue by mdctenga** [grommet/hpe-digitaltoolkit#138]
## Objective

- Show "..." when truncating section text
![three dots show](https://cloud.githubusercontent.com/assets/8364525/18891781/8293cf56-84a2-11e6-82eb-5471c0026a18.png)

### Steps to Reproduce

1. In Android / Firefox notice that the "..." for truncation are replaced with a white block ![three dots do not show](https://cloud.githubusercontent.com/assets/8364525/18891683/1105af9e-84a2-11e6-93a8-c7182dd9542a.png)

**Comment by jwijay** [comment]
Closing this issue, since we're no longer truncating section text on responsive:
![screen shot 2016-10-03 at 2 12 38 pm](https://cloud.githubusercontent.com/assets/10161095/19058494/8383e65a-8973-11e6-8bf1-2446be32edb8.png)

(screenshot of responsive section component)
