### ISSUE TITLE
(Windows10/IE11) Cards are stacking on top of each other in desktop

### ISSUE THREAD

**Issue by mdctenga** [grommet/hpe-digitaltoolkit#144]
## Objective

- ![screen shot 2016-10-03 at 11 07 12 am](https://cloud.githubusercontent.com/assets/8364525/19054131/a242f578-8959-11e6-8375-48f41c07b161.png)

### Steps to Reproduce

1. In Windows 10 / IE 11,  view the "Card with Tiles wrapper section of [http://hpe-toolkit.herokuapp.com/docs/hpe/examples](http://hpe-toolkit.herokuapp.com/docs/hpe/examples)
    - Notice that the cards look like this: 
![screen shot 2016-10-03 at 11 01 11 am](https://cloud.githubusercontent.com/assets/8364525/19054205/fb30d628-8959-11e6-8f27-71fcce1f9241.png)

**Comment by jwijay** [comment]
PR Pending: https://github.com/grommet/grommet/pull/937
