### ISSUE TITLE
Marquee Edit

### ISSUE THREAD

**Issue by kahaeda** [grommet/hpe-digitaltoolkit#146]
We had Marquee image anchored to the left on responsive so that main image area will show for the marquee example on this site.
http://hpe-toolkit.herokuapp.com/docs/hpe/primary
but it looks like it is anchored to the right. 

For images that has main objects on the left please anchor the image on the left. COuld you make that change please? thanks!

**Comment by jwijay** [comment]
PR pending: https://github.com/grommet/hpe-digitaltoolkit/pull/151
