### ISSUE TITLE
(Windows 10/IE11) Section text is smushed

### ISSUE THREAD

**Issue by mdctenga** [grommet/hpe-digitaltoolkit#147]
## Objective

![screen shot 2016-10-04 at 11 12 15 am](https://cloud.githubusercontent.com/assets/8364525/19092695/8238d8cc-8a23-11e6-9666-f0f3a4dba98c.png)

### Steps to Reproduce

1. Navigate to [http://hpe-toolkit.herokuapp.com/docs/hpe/examples](http://hpe-toolkit.herokuapp.com/docs/hpe/examples) on Windows 10/IE11
    - Notice the text is smushed in all of the section component examples ![screen shot 2016-10-04 at 11 10 11 am](https://cloud.githubusercontent.com/assets/8364525/19092661/62447a1c-8a23-11e6-8605-a4b7bdc7aa48.png)

**Comment by jwijay** [comment]
PR Pending: https://github.com/grommet/grommet/pull/937
