### ISSUE TITLE
(Windows 10/IE11) Card text is smushed

### ISSUE THREAD

**Issue by mdctenga** [grommet/hpe-digitaltoolkit#148]
## Objective

![screen shot 2016-10-04 at 11 44 20 am](https://cloud.githubusercontent.com/assets/8364525/19093721/f44ffae0-8a27-11e6-9bb4-640b361e55bf.png)

### Steps to Reproduce

1. Navigate to [http://hpe-toolkit.herokuapp.com/docs/hpe/examples](http://hpe-toolkit.herokuapp.com/docs/hpe/examples) on Windows 10/IE11.
    - Notice that the text in the "Card with Columns wrapper, masonry option" section look like this ![screen shot 2016-10-04 at 11 20 59 am](https://cloud.githubusercontent.com/assets/8364525/19093682/c792ab60-8a27-11e6-8051-2a16f2ccf6f9.png)

**Comment by jwijay** [comment]
PR Pending: https://github.com/grommet/grommet/pull/937
