### ISSUE TITLE
(Windows 10/ IE11) Section Marquee 1 & 2 text is wrong color

### ISSUE THREAD

**Issue by mdctenga** [grommet/hpe-digitaltoolkit#154]
### Correct:
![screen shot 2016-10-17 at 11 00 19 am](https://cloud.githubusercontent.com/assets/8364525/19455530/02a0d19c-9459-11e6-89b0-dc4fe938e12f.png)

### Incorrect:
- Also occurring on Windows 10/ Edge
![incorrect](https://cloud.githubusercontent.com/assets/8364525/19455487/df14ddc2-9458-11e6-85c9-8b4fcfc68f36.png)

Resources:
- Section designs: https://github.com/grommet/hpe-digitaltoolkit-design/issues/31

**Comment by davidcalhoun** [comment]
Narrowed this down to hasDarkBackground in utils/DOM.  Looks like getComputedStyle with IE returns `transparent` here, whereas in other browsers it returns an rgb value (e.g. `rgb(255, 255, 255)`).

Looking for a good cross-browser solution to this, without traversing down to child elements.
