### ISSUE TITLE
Accordion

### ISSUE THREAD

**Issue by jwijay** [grommet/hpe-digitaltoolkit#20]
Waiting on final design assets.

**Comment by kylechristopherb** [comment]
Final design assets are ready.

**Comment by georgediaz** [comment]
[hpe-accordion.pdf](https://github.com/grommet/hpe-digitaltoolkit/files/307955/hpe-accordion.pdf)

**Comment by epilande** [comment]
[accordion-content-modules.pdf](https://github.com/grommet/hpe-digitaltoolkit/files/317325/accordion-content-modules.pdf)

**Comment by kyle-locke** [comment]
video prototypes: https://hpenterprise-my.sharepoint.com/personal/kyle_e_locke_hpe_com/Documents/hpe-digital-toolkit/accordian
