### ISSUE TITLE
Marquee - Background image positioning

### ISSUE THREAD

**Issue by georgediaz** [grommet/hpe-digitaltoolkit#27]
Custom responsive positioning of background image, to allow the user to "stick" the image to the top left, top right, or top center

For responsive, crop the image instead of resizing.

**Comment by georgediaz** [comment]
"crop the image instead of resizing" - not a bug, image must resize for certain browser sizes to avoid awkward whitespace due to image proportions

**Comment by codeswan** [comment]
Closing this out, going to create new issues for each individual request.
