### ISSUE TITLE
Marquee - Update 'small" size

### ISSUE THREAD

**Issue by georgediaz** [grommet/hpe-digitaltoolkit#28]
Change `small` size for Marquee to be 60% of browser height
Responsive headline sizing
  browser width > 1024px, headline should be 64px
  1024px > browser width > 720px, headline should be 48px
  browser width < 720px, headline should be 36px
Add example image with dark theme
Check to see if margin sizes are consistent  - (margin sizes are consistent).

**Comment by codeswan** [comment]
Closing this out, going to create new issues for each individual request.
