### ISSUE TITLE
Card Component

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-digitaltoolkit#31]
http://hpe-styleguide.webmocha.com/module-guide/content-card
http://hpe-styleguide.webmocha.com/module-guide/category-router
http://hpe-styleguide.webmocha.com/module-guide/featured-products
http://hpe-styleguide.webmocha.com/module-guide/text-only-router
http://hpe-styleguide.webmocha.com/module-guide/featured-router
http://hpe-styleguide.webmocha.com/module-guide/hybrid-router

**Comment by jwijay** [comment]
PR pending: https://github.com/grommet/hpe-digitaltoolkit/pull/85
using previously named Callout component (from Accordion) as base, and adding direction option to use Tile-like styles.

![screen shot 2016-06-22 at 12 00 55 pm](https://cloud.githubusercontent.com/assets/10161095/16285318/25e61b06-3871-11e6-95fe-5bf28817e108.png)

**Comment by MikeWalrath** [comment]
https://grommet.slack.com/files/lozzi/F1L7DK27K/card_anatomy.txt

**Comment by kylechristopherb** [comment]
PDF File:
[hpe-cards-v10-kb.pdf](https://github.com/grommet/hpe-digitaltoolkit/files/378774/hpe-cards-v10-kb.pdf)

Sketch File:
[hpe-cards-v10-kb.zip](https://github.com/grommet/hpe-digitaltoolkit/files/378823/hpe-cards-v10-kb.zip)

**Comment by kylechristopherb** [comment]
Card Component Files (zip):
[hpe-card-component.zip](https://github.com/grommet/hpe-digitaltoolkit/files/379142/hpe-card-component.zip)

**Comment by jwijay** [comment]
ContentCard component has been merged and is on toolkit heroku site (ready for design review/qa):
http://hpe-toolkit.herokuapp.com/docs/hpe/develop/contentcard

**Comment by kyle-locke** [comment]
@jwijay

Custom icon colors
Twitter = #1DA1F2
facebook = #3B5998
Linkedin = #0077B5

Thanks!

**Comment by jwijay** [comment]
Updated ContentCard with requested changes from design review:
* custom social icon colors
* custom video watch icon (anchor icon + thumbnail image icon)
* fixed horizontal option width

PR pending: https://github.com/grommet/hpe-digitaltoolkit/pull/112

**Comment by jwijay** [comment]
Grommet-Core PR pending: https://github.com/grommet/grommet/pull/784
