### ISSUE TITLE
Marquee - Change width of text box to 45% of window

### ISSUE THREAD

**Issue by codeswan** [grommet/hpe-digitaltoolkit#54]
Box containing text should only be 45% wide - this includes the margins of the Box.

**Comment by mdctenga** [comment]
In the [docs](http://experienceguide.int.hpe.com/module-guide/featured-products), there's a few different modules that could contain text.  Were you referring to 45% of a specific module?

**Comment by codeswan** [comment]
@mdctenga - My apologies, I should have been clearer.  All of these issues that I added are for the Marquee, however I'll go back and add that clarification now.

Also, just wondering if there's a reason you're mentioning the experience guide?  As far as I know, from a testing perspective the experience guide is not really relevant to the current development, since that's all going to be discarded once the new designs/components are finished.

**Comment by mdctenga** [comment]
@codeswan 
![Text box is 2 px larger than 45% of the marquee.](https://cloud.githubusercontent.com/assets/8364525/16058403/fdc20dd6-3219-11e6-95e2-400cffaf6741.png)

1. Is this within acceptable limits, or are we aiming for pixel perfect?
2. ![Or is this the box I should be measuring?](https://cloud.githubusercontent.com/assets/8364525/16058463/600cf942-321a-11e6-8335-4b7e23a2ef77.png)

**Comment by codeswan** [comment]
@mdctenga In response to your questions:
1. This is approximate, it should be very close but does not have to be pixel-perfect.
2. Yes, it should include the padding.
3. No, for mobile it should fill the whole screen (with a small margin, as shown).

Also, this issue has been overridden by issue #65 - the width should now be 50% instead of 45%.
