### ISSUE TITLE
Marquee - Height of background image should be 270px for mobile

### ISSUE THREAD

**Issue by codeswan** [grommet/hpe-digitaltoolkit#56]
Mobile is defined as anything under the `palm` breakpoint, which is 720px.

**Comment by mdctenga** [comment]
Environment:
- Chrome Version 51.0.2704.84 (64-bit)

![Marquee height is 300px in mobile width when it should be 270px](https://cloud.githubusercontent.com/assets/8364525/16059644/99dc9664-321f-11e6-903f-ac1909bcad21.png)

**Comment by codeswan** [comment]
My apologies for not mentioning this earlier - for the `large` version of the Marquee, this has been overridden by issue #69 (which means the 300px height is correct for the `large` Marquee).
