### ISSUE TITLE
Marquee - Responsive headline sizing

### ISSUE THREAD

**Issue by codeswan** [grommet/hpe-digitaltoolkit#60]
window width > 1024px, headline should be 64px
  1024px > window width > 720px, headline should be 48px
  window width < 720px, headline should be 36px

**Comment by codeswan** [comment]
Also, see issue #63 for update to middle size

**Comment by mdctenga** [comment]
In the [docs](http://experienceguide.int.hpe.com/module-guide/featured-products), I didn't see any module called "headline".  Are you referring to the marquee?

**Comment by codeswan** [comment]
@mdctenga - My apologies, I should have been clearer.  All of these issues that I added are for the Marquee, however I'll go back and add that clarification now.

Also, just wondering if there's a reason you're mentioning the experience guide?  As far as I know, from a testing perspective the experience guide is not really relevant to the current development, since that's all going to be discarded once the new designs/components are finished.

**Comment by mdctenga** [comment]
@codeswan Ah, okay.

**Comment by mdctenga** [comment]
Environment:
- OS: Windows 10
Browser:
- Edge version 20.10240.16384.0
- IE11 version 11.0.10240.16683

What should happen:
- Headline font-size should be 36 px in a browser width from 720 to 1023 px.

Issue:
- Headline font-size remains 64 px at browser widths 1023 px and wider.

Notes:
- Headline font-size changes to 36 px at 1022 px

**Comment by codeswan** [comment]
@mdctenga - The breakpoints are defined by Grommet and cannot be changed.  If this is only an issue of the font-size changing just one pixel too soon, I think this is probably acceptable behavior (as opposed to if it were 100px off or something like that).
