### ISSUE TITLE
Marquee : Text Div Size

### ISSUE THREAD

**Issue by georgediaz** [grommet/hpe-digitaltoolkit#65]
50% text 50% image (follow Grommet size)

**Comment by codeswan** [comment]
@kahaeda This has been implemented, and is now on the staging site.

**Comment by mdctenga** [comment]
In [#54](https://github.com/grommet/hpe-digitaltoolkit/issues/54), it was mentioned that this ticket's 50% should also included the text box's padding and is approximate (no need pixel perfect).  In this example, the marquee width is 1000px and the text box's width (with padding) is 548px.

Which is more acceptable way to look at this:
1. 548px is 54.8% of the marquee width. That rounds down to 50%, so this feature meets the 50% width requirement.
2. The text box generally looks 50% That's good enough.
3. 54.8% is too big. Text box width should be within a smaller percentage of the goal (please provide acceptable range).

Is 54.8% close enough?
![Is 54.8% close enough?](https://cloud.githubusercontent.com/assets/8364525/16062968/5ec308ca-3232-11e6-8070-67fd6d9ed5d9.png)

**Comment by codeswan** [comment]
@mdctenga It looks like you're looking at an old version of the page.  There was an update pushed a couple of hours ago that should address your concerns.

**Comment by mdctenga** [comment]
@kahaeda Passed QA on the following:
- Chrome (OSX / Windows 10 / Android Lollipop / iOS 10)
- Firefox (OSX / Windows 10 / Android Lollipop / iOS 10)
- Safari (OSX, iOS 10)
- IE11 (Windows 10)
- Edge (Windows 10)

**Comment by kahaeda** [comment]
Looks good on my end. Thanks!
