### ISSUE TITLE
Marquee: Center text

### ISSUE THREAD

**Issue by georgediaz** [grommet/hpe-digitaltoolkit#66]

**Comment by georgediaz** [comment]
![screen shot 2016-06-10 at 12 23 07 pm](https://cloud.githubusercontent.com/assets/445559/16016951/57dd3fc0-3152-11e6-8b69-abac410071c7.png)

**Comment by codeswan** [comment]
@kahaeda It's not clear what text should be centered, or how?

**Comment by kahaeda** [comment]
@codeswan from the screenshot, the text is cropped off at the top and not centered from the height of the marquee

**Comment by kahaeda** [comment]
@codeswan I think this was just a bug. I dont see the cropped text anymore
