### ISSUE TITLE
Marquee: Mobile Parallax

### ISSUE THREAD

**Issue by georgediaz** [grommet/hpe-digitaltoolkit#67]
Add Parallax effect on Mobile screen as well (refer to Kahae's .mov file prototyping the behavior)

**Comment by codeswan** [comment]
The parallax effect already exists on the mobile screen.

**Comment by kahaeda** [comment]
Hi @codeswan Parallax does work on desktop but it doesn't work on my phone.. Could you check on it again please? I am using IOS 9.3.2

**Comment by kahaeda** [comment]
@codeswan The parallax works on Android but doesn't work on IOS.

**Comment by kahaeda** [comment]
@mdctenga @codeswan zoom in animation is jerky. Animation needs to be smoother

**Comment by codeswan** [comment]
@mdctenga Chris informed me today that they have decided we will be removing the parallax functionalities, so this issue can be closed as it is no longer valid.  See new issue #88
