### ISSUE TITLE
Marquee : Mobile & Tablet Marquee

### ISSUE THREAD

**Issue by georgediaz** [grommet/hpe-digitaltoolkit#68]
Add option to add grey rule at the end of the Marquee

**Comment by georgediaz** [comment]
<img width="319" alt="screen shot 2016-06-10 at 2 01 19 pm" src="https://cloud.githubusercontent.com/assets/445559/16016878/fc31a968-3151-11e6-9d6f-043a4159318f.png">

**Comment by codeswan** [comment]
@kahaeda This has been implemented, and is now on the staging site.
