### ISSUE TITLE
Marquee: replace image to the new ones

### ISSUE THREAD

**Issue by georgediaz** [grommet/hpe-digitaltoolkit#70]

**Comment by georgediaz** [comment]
![tk_marquee_image](https://cloud.githubusercontent.com/assets/445559/16016716/386fdb8a-3151-11e6-9f5e-13eccb938a6a.jpg)
![marqueeimage_051916_small](https://cloud.githubusercontent.com/assets/445559/16016722/3c5fb616-3151-11e6-921d-1e8961a74ea9.jpg)

**Comment by kahaeda** [comment]
Please use these images
Large Marquee : 
![marqueeimage_061016](https://cloud.githubusercontent.com/assets/3943989/16017501/15863d0e-3155-11e6-90a8-84a3819b5cc9.jpg)

Small Marquee:
![marqueeimage_061016_small](https://cloud.githubusercontent.com/assets/3943989/16017714/f08ac44c-3155-11e6-948e-a7b59401dc0d.jpg)

**Comment by codeswan** [comment]
@kahaeda This has been implemented, and is now on the staging site.
