### ISSUE TITLE
Marquee: Parallax zooming out.

### ISSUE THREAD

**Issue by georgediaz** [grommet/hpe-digitaltoolkit#74]
Vasken would like to see how the parallax would look like with Image zooming out instead of zooming in.

**Comment by codeswan** [comment]
@kahaeda This has been implemented, and is available to view on the staging site.  I have left the third marquee zooming in, so that you can see for the sake of comparison to help Vasken decide which he prefers.

**Comment by kahaeda** [comment]
@codeswan After reviewing with Vasken again, we think the zooming in effect was working better. Could you please change it back to zoom in? Thanks! Please let me know if you would like me to add another card
