### ISSUE TITLE
Video Marquee

### ISSUE THREAD

**Issue by kahaeda** [grommet/hpe-digitaltoolkit#89]

**Comment by prewalia** [comment]
Hey guys here are the Video Marquess option, due to the file size limitation I will have to upload 3 different option in 3-6 posts! :) Sorry about that, if you guys know a way to upload files larger than 10 MB please let me know..

**CONCEPT 1**
File Name: VideoMarque_Part1

[VideoMarque_Part1.zip](https://github.com/grommet/hpe-digitaltoolkit/files/332448/VideoMarque_Part1.zip)

**Comment by prewalia** [comment]
**CONCEPT 2**
File Name: VideoMarque_Part2

[VideoMarque_Part2.zip](https://github.com/grommet/hpe-digitaltoolkit/files/332452/VideoMarque_Part2.zip)

**Comment by prewalia** [comment]
**CONCEPT 3**
We had two video for this option

File Name(s):

VideoMarque_Part3V1: 
[VideoMarque_Part3V1.zip](https://github.com/grommet/hpe-digitaltoolkit/files/332493/VideoMarque_Part3V1.zip)

VideoMarque_Part3V2:
[VideoMarque_Part3V2.zip](https://github.com/grommet/hpe-digitaltoolkit/files/332495/VideoMarque_Part3V2.zip)

**Comment by prewalia** [comment]
VideoMarque_Part3V3:
[VideoMarque_Part3V3.zip](https://github.com/grommet/hpe-digitaltoolkit/files/332496/VideoMarque_Part3V3.zip)

**Comment by prewalia** [comment]
Hey guys i've created a folder which has the following:

All the video used under a folder named: Video Used in the Marquee
A pdf so you guys can see everything
And a MOV playing all the video at home

Here is the link: https://www.dropbox.com/sh/g61kr3yd0wi51j0/AACRxwP7NKvusBzwYr1fsmGKa?dl=0

Let me know if something doesn't make sense!

Thank you,
Pre

**Comment by kyle-locke** [comment]
[hpe-video-component-r2-kl.pdf](https://github.com/grommet/hpe-digitaltoolkit/files/387378/hpe-video-component-r2-kl.pdf)

**Comment by kyle-locke** [comment]
[hpe-video-component-r2-kl.sketch.zip](https://github.com/grommet/hpe-digitaltoolkit/files/387379/hpe-video-component-r2-kl.sketch.zip)

**Comment by kyle-locke** [comment]
[Uploading hpe-video-component-r2-kl.pdf…]()
[hpe-video-component-r2-kl.sketch.zip](https://github.com/grommet/hpe-digitaltoolkit/files/387399/hpe-video-component-r2-kl.sketch.zip)

**Comment by kyle-locke** [comment]
[hpe-video-component-r2-kl.pdf](https://github.com/grommet/hpe-digitaltoolkit/files/387420/hpe-video-component-r2-kl.pdf)

[hpe-video-component-r2-kl.sketch.zip](https://github.com/grommet/hpe-digitaltoolkit/files/387421/hpe-video-component-r2-kl.sketch.zip)

**Comment by kahaeda** [comment]
Video Marquee Type size changes: Change the text to Xlarge stack component ( Headline to Xlarge heading (64px) and sub text to Lead paragraph (24px)

**Comment by kyle-locke** [comment]
[hpe-video-component-r4-kl.zip](https://github.com/grommet/hpe-digitaltoolkit/files/415855/hpe-video-component-r4-kl.zip)

**Comment by kyle-locke** [comment]
@codeswan ^updated video player with new icon styles. invision link: https://hp.invisionapp.com/share/NY7ZQYUJG

**Comment by prewalia** [comment]
Hey guys I've updated the Video marquee with the new icons :) here is the link:
https://hp.invisionapp.com/share/ZT86D8AAH

Let me know if you have any questions.
Thanks,
Pre

**Comment by kyle-locke** [comment]
New icon in SVG format.
[Watch Icon.svg.zip](https://github.com/grommet/hpe-digitaltoolkit/files/416246/Watch.Icon.svg.zip)

**Comment by kahaeda** [comment]
@codeswan  Here is the comp! Sorry thought I've uploaded. 
![marquee_watchnow_v5_081516-03]
(https://cloud.githubusercontent.com/assets/3943989/17681505/0f9ad7e2-62fb-11e6-926c-e755ebe50a65.jpg)

It is basically adding a "Watch Now" Link CTA next to learn more button. 
Let me know if you have any questions. 
Thanks!
