### ISSUE TITLE
Box Component (Layout Wrapper)

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/hpe-digitaltoolkit#94]
Includes 
1 Column 
http://hpe-styleguide.webmocha.com/module-guide/1-column

2 Column 50/50
http://hpe-styleguide.webmocha.com/module-guide/2-column-50-50

2 Column 33/66
http://hpe-styleguide.webmocha.com/module-guide/2-column-33-66

3 Column
http://hpe-styleguide.webmocha.com/module-guide/3-column-33-33-33

4 Column
http://hpe-styleguide.webmocha.com/module-guide/4-column-25-25-25-25

**Comment by MikeWalrath** [comment]
PR pending review: #79

**Comment by jwijay** [comment]
PR pending review: https://github.com/grommet/hpe-digitaltoolkit/pull/106
(related grommet PR also pending).

**Comment by jwijay** [comment]
Based on hpe-digitaltoolkit-design:
https://github.com/grommet/hpe-digitaltoolkit-design/issues/33

Note that for the 1140px fixed width designs, grommet only supports up to 960px fixed-width by using the `size={{"width": {"max": "xxlarge"}}}` option, as shown in the Columns (1/3 Basis) example:
http://hpe-toolkit.herokuapp.com/docs/hpe/develop/box"

For the 1-Column design, 82%/83% widths are not supported, and instead the `basis="3/4"` option (75% width) can be used, or `size={{"width": {"max": "xxlarge"}}}` (max-width 960px).
